-- ==========================================
-- COMPLETE WHATDOSE DATABASE SCHEMA
-- ==========================================
-- This script creates all tables, types, policies, and seed data
-- needed for the complete WhatDose application.
-- ==========================================

-- ==========================================
-- 1. CLEANUP (För att kunna köra scriptet flera gånger vid dev)
-- ==========================================

DROP TABLE IF EXISTS daily_task_completions CASCADE;
DROP TABLE IF EXISTS timeline_items CASCADE;
DROP TABLE IF EXISTS timeline_blocks CASCADE;
DROP TABLE IF EXISTS user_progress_metrics CASCADE;
DROP TABLE IF EXISTS stack_comments CASCADE;
DROP TABLE IF EXISTS stack_likes CASCADE;
DROP TABLE IF EXISTS community_stacks CASCADE;
DROP TABLE IF EXISTS user_goals CASCADE;
DROP TABLE IF EXISTS daily_checkins CASCADE;
DROP TABLE IF EXISTS daily_logs CASCADE;
DROP TABLE IF EXISTS user_stacks CASCADE;
DROP TABLE IF EXISTS supplements CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

DROP TYPE IF EXISTS research_status_type CASCADE;
DROP TYPE IF EXISTS regulatory_type CASCADE;
DROP TYPE IF EXISTS unit_type CASCADE;
DROP TYPE IF EXISTS risk_level_type CASCADE;
DROP TYPE IF EXISTS schedule_block_type CASCADE;

-- ==========================================
-- 2. ENUMS & TYPES (Standardiserade värden)
-- ==========================================

CREATE TYPE research_status_type AS ENUM ('Green', 'Blue', 'Yellow', 'Red');
CREATE TYPE regulatory_type AS ENUM ('Supplement', 'Medicine', 'Grey Zone', 'Restricted');
CREATE TYPE unit_type AS ENUM ('mg', 'g', 'IU', 'mcg', 'ml', 'tabs', 'caps', 'cfu');
CREATE TYPE risk_level_type AS ENUM ('Low', 'Medium', 'High');
CREATE TYPE schedule_block_type AS ENUM ('Morning', 'Lunch', 'Pre-Workout', 'Post-Workout', 'Dinner', 'Bedtime');

-- ==========================================
-- 3. CORE TABLES
-- ==========================================

-- A. PROFILES (Kopplat till Supabase Auth)
CREATE TABLE profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    first_name TEXT,
    goal_profile TEXT, -- t.ex. 'Muscle', 'Sleep', 'Longevity'
    experience_level TEXT, -- 'Beginner', 'Biohacker'
    onboarding_completed BOOLEAN DEFAULT FALSE,
    -- Biometrics (added for onboarding)
    age INT,
    weight_kg NUMERIC(5,2),
    gender TEXT, -- 'male', 'female', 'other'
    -- Selected goals as array (alternative to user_goals table)
    selected_goals TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- B. SUPPLEMENTS LIBRARY (Master-databasen)
CREATE TABLE supplements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_sv TEXT, 
    name_en TEXT NOT NULL,
    research_status research_status_type DEFAULT 'Blue',
    regulatory_status regulatory_type DEFAULT 'Supplement',
    dosing_base_val NUMERIC,
    dosing_max_val NUMERIC,
    unit unit_type,
    dosing_notes TEXT,
    bioavailability_notes TEXT,
    interaction_risk_text TEXT,
    interaction_risk_level risk_level_type DEFAULT 'Low',
    is_base_health BOOLEAN DEFAULT FALSE,
    category_ids INT[], -- 1=Health, 2=Muscle, 3=Performance, 4=Focus, 5=Stress, 6=Metabolic, 7=Sleep, 8=Anti-Aging, 9=Joints
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- C. USER STACKS (Vad användaren har lagt till i sitt schema)
CREATE TABLE user_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    supplement_id BIGINT REFERENCES supplements(id) ON DELETE CASCADE NOT NULL,
    
    -- Användaren kan överskrida standard-dosering
    custom_dosage_val NUMERIC, 
    schedule_block schedule_block_type DEFAULT 'Morning',
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    
    -- Unikt constraint: Man kan inte lägga till samma tillskott två gånger i samma tidsblock
    UNIQUE(user_id, supplement_id, schedule_block)
);

-- D. DAILY LOGS (Tracking av individuella doser)
CREATE TABLE daily_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    stack_item_id BIGINT REFERENCES user_stacks(id) ON DELETE CASCADE,
    
    taken_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    status TEXT DEFAULT 'taken', -- 'taken', 'skipped'
    
    log_date DATE DEFAULT CURRENT_DATE
);

-- E. DAILY CHECKINS (Chatt-datan: Humör, Sömn, Biverkningar)
CREATE TABLE daily_checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    
    date DATE DEFAULT CURRENT_DATE,
    sleep_score INT, -- 1-100
    energy_tag TEXT, -- 'High', 'Low', etc
    side_effects TEXT[], -- Array av tags t.ex. ['Nausea', 'Headache']
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, date)
);

-- ==========================================
-- 4. TIMELINE & TASK TRACKING
-- ==========================================

-- F. TIMELINE BLOCKS (Morning, Pre-Workout, Bedtime, etc.)
CREATE TABLE timeline_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    block_id TEXT NOT NULL, -- 'morning_routine', 'pre_workout', 'bedtime', etc.
    title TEXT NOT NULL,
    subtitle TEXT,
    suggested_time TIME,
    ui_color_hex TEXT,
    icon_key TEXT,
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, block_id)
);

-- G. TIMELINE ITEMS (Individual supplements/tasks within blocks)
CREATE TABLE timeline_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT REFERENCES timeline_blocks(id) ON DELETE CASCADE NOT NULL,
    stack_item_id BIGINT REFERENCES user_stacks(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL, -- Unique identifier for the item
    display_order INT DEFAULT 0,
    notes TEXT,
    critical_instruction TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- H. DAILY TASK COMPLETIONS (Tracking completion per day)
CREATE TABLE daily_task_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    item_id TEXT NOT NULL, -- References timeline_items.item_id
    completion_date DATE DEFAULT CURRENT_DATE,
    is_completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, item_id, completion_date)
);

-- ==========================================
-- 5. PROGRESS METRICS
-- ==========================================

-- I. USER PROGRESS METRICS (Cached metrics for performance)
CREATE TABLE user_progress_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    metric_date DATE DEFAULT CURRENT_DATE,
    streak_days INT DEFAULT 0,
    total_tasks INT DEFAULT 0,
    completed_tasks INT DEFAULT 0,
    compliance_percentage NUMERIC(5,2) DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, metric_date)
);

-- ==========================================
-- 6. COMMUNITY FEATURES
-- ==========================================

-- J. COMMUNITY STACKS (Shared stacks by users)
CREATE TABLE community_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    supplements JSONB NOT NULL, -- Array of {name, dosage} objects
    result_description TEXT, -- What results the user achieved
    likes_count INT DEFAULT 0,
    comments_count INT DEFAULT 0,
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- K. STACK LIKES (Likes on community stacks)
CREATE TABLE stack_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stack_id BIGINT REFERENCES community_stacks(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(stack_id, user_id)
);

-- L. STACK COMMENTS (Comments on community stacks)
CREATE TABLE stack_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stack_id BIGINT REFERENCES community_stacks(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- ==========================================
-- 7. USER GOALS (Alternative to selected_goals array)
-- ==========================================

-- M. USER GOALS (Normalized goals table)
CREATE TABLE user_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    goal_id TEXT NOT NULL, -- 'muscle', 'sleep', 'focus', 'longevity', etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(user_id, goal_id)
);

-- ==========================================
-- 8. INDEXES (For performance)
-- ==========================================

CREATE INDEX idx_user_stacks_user_id ON user_stacks(user_id);
CREATE INDEX idx_user_stacks_supplement_id ON user_stacks(supplement_id);
CREATE INDEX idx_daily_logs_user_id ON daily_logs(user_id);
CREATE INDEX idx_daily_logs_log_date ON daily_logs(log_date);
CREATE INDEX idx_daily_checkins_user_id ON daily_checkins(user_id);
CREATE INDEX idx_daily_checkins_date ON daily_checkins(date);
CREATE INDEX idx_timeline_blocks_user_id ON timeline_blocks(user_id);
CREATE INDEX idx_timeline_items_block_id ON timeline_items(block_id);
CREATE INDEX idx_daily_task_completions_user_id ON daily_task_completions(user_id);
CREATE INDEX idx_daily_task_completions_date ON daily_task_completions(completion_date);
CREATE INDEX idx_user_progress_metrics_user_id ON user_progress_metrics(user_id);
CREATE INDEX idx_user_progress_metrics_date ON user_progress_metrics(metric_date);
CREATE INDEX idx_community_stacks_user_id ON community_stacks(user_id);
CREATE INDEX idx_community_stacks_is_public ON community_stacks(is_public);
CREATE INDEX idx_stack_likes_stack_id ON stack_likes(stack_id);
CREATE INDEX idx_stack_comments_stack_id ON stack_comments(stack_id);

-- ==========================================
-- 9. SECURITY (Row Level Security - RLS)
-- ==========================================

-- Aktivera RLS på alla tabeller
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplements ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_stacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeline_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE timeline_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE community_stacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE stack_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE stack_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Profiles: Users can only see/edit their own profile
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Supplements: Public read, Admin write (ingen write policy här = read only för users)
CREATE POLICY "Supplements are public" ON supplements FOR SELECT USING (true);

-- User Stacks: Users manage their own stacks
CREATE POLICY "Users view own stack" ON user_stacks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own stack" ON user_stacks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own stack" ON user_stacks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own stack" ON user_stacks FOR DELETE USING (auth.uid() = user_id);

-- Logs & Checkins: Strictly private
CREATE POLICY "Users view own logs" ON daily_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own logs" ON daily_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own logs" ON daily_logs FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users view own checkins" ON daily_checkins FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own checkins" ON daily_checkins FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own checkins" ON daily_checkins FOR UPDATE USING (auth.uid() = user_id);

-- Timeline Blocks: Users manage their own
CREATE POLICY "Users view own timeline blocks" ON timeline_blocks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own timeline blocks" ON timeline_blocks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own timeline blocks" ON timeline_blocks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own timeline blocks" ON timeline_blocks FOR DELETE USING (auth.uid() = user_id);

-- Timeline Items: Users manage their own (via block ownership)
CREATE POLICY "Users view own timeline items" ON timeline_items FOR SELECT 
    USING (EXISTS (
        SELECT 1 FROM timeline_blocks 
        WHERE timeline_blocks.id = timeline_items.block_id 
        AND timeline_blocks.user_id = auth.uid()
    ));
CREATE POLICY "Users insert own timeline items" ON timeline_items FOR INSERT 
    WITH CHECK (EXISTS (
        SELECT 1 FROM timeline_blocks 
        WHERE timeline_blocks.id = timeline_items.block_id 
        AND timeline_blocks.user_id = auth.uid()
    ));
CREATE POLICY "Users update own timeline items" ON timeline_items FOR UPDATE 
    USING (EXISTS (
        SELECT 1 FROM timeline_blocks 
        WHERE timeline_blocks.id = timeline_items.block_id 
        AND timeline_blocks.user_id = auth.uid()
    ));
CREATE POLICY "Users delete own timeline items" ON timeline_items FOR DELETE 
    USING (EXISTS (
        SELECT 1 FROM timeline_blocks 
        WHERE timeline_blocks.id = timeline_items.block_id 
        AND timeline_blocks.user_id = auth.uid()
    ));

-- Daily Task Completions: Users manage their own
CREATE POLICY "Users view own task completions" ON daily_task_completions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own task completions" ON daily_task_completions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own task completions" ON daily_task_completions FOR UPDATE USING (auth.uid() = user_id);

-- Progress Metrics: Users view their own
CREATE POLICY "Users view own progress metrics" ON user_progress_metrics FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own progress metrics" ON user_progress_metrics FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own progress metrics" ON user_progress_metrics FOR UPDATE USING (auth.uid() = user_id);

-- Community Stacks: Public read, users can create/update their own
CREATE POLICY "Community stacks are public" ON community_stacks FOR SELECT USING (is_public = true OR auth.uid() = user_id);
CREATE POLICY "Users insert own community stacks" ON community_stacks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own community stacks" ON community_stacks FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own community stacks" ON community_stacks FOR DELETE USING (auth.uid() = user_id);

-- Stack Likes: Public read, users manage their own
CREATE POLICY "Stack likes are public" ON stack_likes FOR SELECT USING (true);
CREATE POLICY "Users insert own likes" ON stack_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own likes" ON stack_likes FOR DELETE USING (auth.uid() = user_id);

-- Stack Comments: Public read, users manage their own
CREATE POLICY "Stack comments are public" ON stack_comments FOR SELECT USING (true);
CREATE POLICY "Users insert own comments" ON stack_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own comments" ON stack_comments FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users delete own comments" ON stack_comments FOR DELETE USING (auth.uid() = user_id);

-- User Goals: Users manage their own
CREATE POLICY "Users view own goals" ON user_goals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own goals" ON user_goals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own goals" ON user_goals FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 10. AUTOMATION (Triggers & Functions)
-- ==========================================

-- Skapa automatiskt en profil när en ny användare registrerar sig
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name)
  VALUES (new.id, new.raw_user_meta_data->>'first_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Update likes_count when likes are added/removed
CREATE OR REPLACE FUNCTION update_stack_likes_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE community_stacks 
    SET likes_count = likes_count + 1 
    WHERE id = NEW.stack_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE community_stacks 
    SET likes_count = GREATEST(likes_count - 1, 0)
    WHERE id = OLD.stack_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER stack_likes_count_trigger
  AFTER INSERT OR DELETE ON stack_likes
  FOR EACH ROW EXECUTE FUNCTION update_stack_likes_count();

-- Update comments_count when comments are added/removed
CREATE OR REPLACE FUNCTION update_stack_comments_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE community_stacks 
    SET comments_count = comments_count + 1 
    WHERE id = NEW.stack_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE community_stacks 
    SET comments_count = GREATEST(comments_count - 1, 0)
    WHERE id = OLD.stack_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER stack_comments_count_trigger
  AFTER INSERT OR DELETE ON stack_comments
  FOR EACH ROW EXECUTE FUNCTION update_stack_comments_count();

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = TIMEZONE('utc', NOW());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_timeline_blocks_updated_at BEFORE UPDATE ON timeline_blocks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_timeline_items_updated_at BEFORE UPDATE ON timeline_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_community_stacks_updated_at BEFORE UPDATE ON community_stacks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_stack_comments_updated_at BEFORE UPDATE ON stack_comments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 11. SEED DATA (Fyll Supplements Library)
-- ==========================================

INSERT INTO supplements (
    name_sv, name_en, research_status, regulatory_status, 
    dosing_base_val, dosing_max_val, unit, 
    dosing_notes, bioavailability_notes, interaction_risk_text, interaction_risk_level, 
    is_base_health, category_ids
) VALUES 

-- CREATINE
('Kreatin Monohydrat', 'Creatine Monohydrate', 'Green', 'Supplement', 
 3, 5, 'g', 
 'Maintenance dose 3-5g/day. Optional loading phase: 20g/day for 5-7 days.', 
 'Best taken with carbs/protein for insulin-mediated uptake.', 
 'Low risk. Increases creatinine levels (benign). Drink extra water.', 'Low', 
 FALSE, ARRAY[2, 3, 4, 7]),

-- OMEGA-3
('Omega-3 (EPA/DHA)', 'Omega-3 (EPA/DHA)', 'Green', 'Supplement', 
 2, 4, 'g', 
 'Measure total EPA+DHA. Higher dose (3-4g) required for inflammation control.', 
 'Take with a fatty meal. Triglyceride form is superior to Ethyl Ester.', 
 'May thin blood at doses >3g/day.', 'Medium', 
 TRUE, ARRAY[1, 4, 5, 6, 8, 9]),

-- VITAMIN D3
('Vitamin D3', 'Vitamin D3', 'Green', 'Supplement', 
 2000, 4000, 'IU', 
 'Target blood levels: 75-125 nmol/L. Winter supplementation is critical.', 
 'Fat-soluble - must be taken with dietary fat.', 
 'Toxicity risk at chronic doses >10,000 IU/day.', 'Low', 
 TRUE, ARRAY[1, 2, 5, 8, 9]),

-- MAGNESIUM GLYCINATE
('Magnesium (Glycinat)', 'Magnesium Glycinate', 'Green', 'Supplement', 
 200, 400, 'mg', 
 'Glycinate form for sleep/anxiety. Dose refers to elemental Magnesium.', 
 'High bioavailability. Take in the evening.', 
 'Loose stools at high doses. Competes with Zinc/Calcium absorption.', 'Low', 
 TRUE, ARRAY[1, 5, 7, 9]),

-- MAGNESIUM L-THREONATE
('Magnesium L-Threonat', 'Magnesium L-Threonate', 'Green', 'Supplement', 
 1500, 2000, 'mg', 
 'Specific for cognitive function (~144mg elemental Mg per 2g).', 
 'Uniquely crosses the blood-brain barrier.', 
 'Safe up to 3g. More expensive than other forms.', 'Low', 
 FALSE, ARRAY[4, 5, 7]),

-- MULTIVITAMIN
('Multivitamin/Mineral', 'Multivitamin Complex', 'Green', 'Supplement', 
 1, 2, 'tabs', 
 'Choose a product with methylated folate. Basic insurance.', 
 'Take with your largest meal (for fat-soluble vitamins).', 
 'Avoid double-dosing Vitamin A or Zinc.', 'Low', 
 TRUE, ARRAY[1, 8]),

-- EAA
('EAA', 'Essential Amino Acids', 'Green', 'Supplement', 
 10, 20, 'g', 
 'Contains all 9 essential amino acids. Superior to BCAA.', 
 'Best taken on an empty stomach around training.', 
 'Mild GI distress possible initially.', 'Low', 
 FALSE, ARRAY[2, 3, 7]),

-- CAFFEINE
('Koffein', 'Caffeine', 'Green', 'Supplement', 
 100, 400, 'mg', 
 'Performance: 3-6mg/kg. Max 400mg/day total.', 
 'Peaks in 45 min. Half-life ~5h.', 
 'Disrupts sleep (avoid 6h before bed). Can cause anxiety.', 'Medium', 
 FALSE, ARRAY[3, 4, 6]),

-- L-THEANINE
('L-Teanin', 'L-Theanine', 'Green', 'Supplement', 
 100, 400, 'mg', 
 'Use a 2:1 ratio with Caffeine for focus without the jitters.', 
 'Increases alpha brain waves.', 
 'Very safe. May slightly lower blood pressure.', 'Low', 
 FALSE, ARRAY[4, 5]),

-- ZINC
('Zink (Pikolinat)', 'Zinc Picolinate', 'Green', 'Supplement', 
 15, 30, 'mg', 
 'For testosterone/immunity. Max 40mg long-term.', 
 'Competes with Copper/Iron. Do not take with Calcium.', 
 'Nausea on an empty stomach. Copper deficiency risk at high doses.', 'Medium', 
 FALSE, ARRAY[1, 2, 8]),

-- VITAMIN K2
('Vitamin K2 (MK-7)', 'Vitamin K2 (MK-7)', 'Green', 'Supplement', 
 100, 200, 'mcg', 
 'Directs calcium to bones, away from arteries.', 
 'Fat-soluble. Take with D3.', 
 'Warning: Interacts with Warfarin/Blood thinners.', 'High', 
 TRUE, ARRAY[1, 8, 9]),

-- ASHWAGANDHA
('Ashwagandha (KSM-66)', 'Ashwagandha', 'Green', 'Supplement', 
 300, 600, 'mg', 
 'Lowers cortisol. Root extract preferred.', 
 'Take with food/evening. Cycle: 8 weeks on, 2 off.', 
 'May interact with thyroid medication.', 'Medium', 
 FALSE, ARRAY[5, 7, 8]),

-- BERBERINE
('Berberin HCL', 'Berberine HCL', 'Green', 'Supplement', 
 500, 1500, 'mg', 
 'Glucose regulation ("Nature''s Metformin").', 
 'Split dose 3x/day with carb-heavy meals.', 
 'Interacts with CYP enzymes (medication metabolism).', 'High', 
 FALSE, ARRAY[6, 8]);

-- ==========================================
-- END OF SCHEMA
-- ==========================================

