-- ==========================================
-- SUPPLEMENT VOTING & COMMENTS EXTENSIONS
-- ==========================================
-- Adds upvote/downvote and comments functionality for supplements
-- Run this after complete_schema.sql and other schema extensions
-- ==========================================

-- 1. SUPPLEMENT VOTES (Upvotes/Downvotes)
CREATE TABLE IF NOT EXISTS supplement_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id BIGINT REFERENCES supplements(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    vote_type TEXT NOT NULL CHECK (vote_type IN ('upvote', 'downvote')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    UNIQUE(supplement_id, user_id)
);

-- 2. SUPPLEMENT COMMENTS
CREATE TABLE IF NOT EXISTS supplement_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplement_id BIGINT REFERENCES supplements(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. ADD VOTE COUNTS TO SUPPLEMENTS TABLE (denormalized for performance)
ALTER TABLE supplements 
  ADD COLUMN IF NOT EXISTS upvotes_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS downvotes_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS comments_count INT DEFAULT 0;

-- 4. INDEXES (For performance)
CREATE INDEX IF NOT EXISTS idx_supplement_votes_supplement_id ON supplement_votes(supplement_id);
CREATE INDEX IF NOT EXISTS idx_supplement_votes_user_id ON supplement_votes(user_id);
CREATE INDEX IF NOT EXISTS idx_supplement_comments_supplement_id ON supplement_comments(supplement_id);
CREATE INDEX IF NOT EXISTS idx_supplement_comments_user_id ON supplement_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_supplement_comments_created_at ON supplement_comments(created_at DESC);

-- 5. ROW LEVEL SECURITY

-- Enable RLS
ALTER TABLE supplement_votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplement_comments ENABLE ROW LEVEL SECURITY;

-- Supplement Votes Policies
CREATE POLICY "Anyone can view supplement votes" ON supplement_votes 
  FOR SELECT USING (true);

CREATE POLICY "Users can insert own votes" ON supplement_votes 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own votes" ON supplement_votes 
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own votes" ON supplement_votes 
  FOR DELETE USING (auth.uid() = user_id);

-- Supplement Comments Policies
CREATE POLICY "Anyone can view supplement comments" ON supplement_comments 
  FOR SELECT USING (true);

CREATE POLICY "Users can insert own comments" ON supplement_comments 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own comments" ON supplement_comments 
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own comments" ON supplement_comments 
  FOR DELETE USING (auth.uid() = user_id);

-- 6. TRIGGERS & FUNCTIONS

-- Function to update vote counts when votes are added/updated/deleted
CREATE OR REPLACE FUNCTION update_supplement_vote_counts()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.vote_type = 'upvote' THEN
      UPDATE supplements 
      SET upvotes_count = upvotes_count + 1 
      WHERE id = NEW.supplement_id;
    ELSIF NEW.vote_type = 'downvote' THEN
      UPDATE supplements 
      SET downvotes_count = downvotes_count + 1 
      WHERE id = NEW.supplement_id;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    -- Handle vote type change (upvote <-> downvote)
    IF OLD.vote_type = 'upvote' AND NEW.vote_type = 'downvote' THEN
      UPDATE supplements 
      SET upvotes_count = GREATEST(upvotes_count - 1, 0),
          downvotes_count = downvotes_count + 1
      WHERE id = NEW.supplement_id;
    ELSIF OLD.vote_type = 'downvote' AND NEW.vote_type = 'upvote' THEN
      UPDATE supplements 
      SET upvotes_count = upvotes_count + 1,
          downvotes_count = GREATEST(downvotes_count - 1, 0)
      WHERE id = NEW.supplement_id;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    IF OLD.vote_type = 'upvote' THEN
      UPDATE supplements 
      SET upvotes_count = GREATEST(upvotes_count - 1, 0)
      WHERE id = OLD.supplement_id;
    ELSIF OLD.vote_type = 'downvote' THEN
      UPDATE supplements 
      SET downvotes_count = GREATEST(downvotes_count - 1, 0)
      WHERE id = OLD.supplement_id;
    END IF;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger for vote counts
DROP TRIGGER IF EXISTS supplement_vote_counts_trigger ON supplement_votes;
CREATE TRIGGER supplement_vote_counts_trigger
  AFTER INSERT OR UPDATE OR DELETE ON supplement_votes
  FOR EACH ROW EXECUTE FUNCTION update_supplement_vote_counts();

-- Function to update comment count
CREATE OR REPLACE FUNCTION update_supplement_comments_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE supplements 
    SET comments_count = comments_count + 1 
    WHERE id = NEW.supplement_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE supplements 
    SET comments_count = GREATEST(comments_count - 1, 0)
    WHERE id = OLD.supplement_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger for comment counts
DROP TRIGGER IF EXISTS supplement_comments_count_trigger ON supplement_comments;
CREATE TRIGGER supplement_comments_count_trigger
  AFTER INSERT OR DELETE ON supplement_comments
  FOR EACH ROW EXECUTE FUNCTION update_supplement_comments_count();

-- Update updated_at timestamp for votes
CREATE TRIGGER update_supplement_votes_updated_at 
  BEFORE UPDATE ON supplement_votes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Update updated_at timestamp for comments
CREATE TRIGGER update_supplement_comments_updated_at 
  BEFORE UPDATE ON supplement_comments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 7. INITIALIZE COUNTS FOR EXISTING SUPPLEMENTS (if needed)
-- This will set counts to 0 for supplements that don't have the columns yet
UPDATE supplements 
SET 
  upvotes_count = COALESCE(upvotes_count, 0),
  downvotes_count = COALESCE(downvotes_count, 0),
  comments_count = COALESCE(comments_count, 0)
WHERE upvotes_count IS NULL OR downvotes_count IS NULL OR comments_count IS NULL;

