#!/usr/bin/env python3
"""
Complete translation script for Swedish supplement CSV to English.
Translates all Swedish text including research status, interaction risks, and descriptions.
"""

import csv
import re

# Translation mappings
STATUS_MAP = {
    'Grön': 'Green',
    'Blå': 'Blue',
    'Röd': 'Red'
}

RISK_MAP = {
    'Låg': 'Low',
    'Medium': 'Medium',
    'Hög': 'High'
}

# Common Swedish to English translations for supplement descriptions
SWEDISH_PHRASES = {
    # Research status and risk
    'Grön': 'Green',
    'Blå': 'Blue',
    'Röd': 'Red',
    'Låg': 'Low',
    'Hög': 'High',
    'Medium': 'Medium',
    
    # Common terms
    'mg': 'mg',
    'g': 'g',
    'mcg': 'mcg',
    'IU': 'IU',
    'ml': 'ml',
    'tsk': 'tsp',
    'koppar': 'cups',
    'mdr': 'billion',
    'Mrd': 'billion',
    'B': 'B',
    'CFU': 'CFU',
    'FCC': 'FCC',
    'FU': 'FU',
    'SPK': 'SPK',
    'GDU': 'GDU',
    'HU': 'HU',
    'N/A': 'N/A',
    '-': '-',
    'Varierar': 'Varies',
    'dos': 'dose',
    'doser': 'doses',
}

def translate_text(text):
    """Translate Swedish text to English, preserving technical terms."""
    if not text or text == '-':
        return text
    
    # Replace status and risk values
    for swedish, english in STATUS_MAP.items():
        text = text.replace(swedish, english)
    
    for swedish, english in RISK_MAP.items():
        text = text.replace(swedish, english)
    
    # Common Swedish medical/supplement terms
    translations = {
        'Slem': 'Mucus',
        'lever': 'liver',
        'hud': 'skin',
        'hår': 'hair',
        'naglar': 'nails',
        'ögon': 'eyes',
        'hjärta': 'heart',
        'hjärna': 'brain',
        'mage': 'stomach',
        'tarm': 'intestine',
        'leder': 'joints',
        'muskler': 'muscles',
        'ben': 'bones',
        'prostata': 'prostate',
        'blodtryck': 'blood pressure',
        'blodsocker': 'blood sugar',
        'immun': 'immune',
        'immunförsvar': 'immune defense',
        'energi': 'energy',
        'sömn': 'sleep',
        'stress': 'stress',
        'ångest': 'anxiety',
        'depression': 'depression',
        'humör': 'mood',
        'minne': 'memory',
        'fokus': 'focus',
        'libido': 'libido',
        'testosteron': 'testosterone',
        'inflammation': 'inflammation',
        'antioxidant': 'antioxidant',
        'detox': 'detox',
        'metabolism': 'metabolism',
        'fettförbränning': 'fat burning',
        'muskeltillväxt': 'muscle growth',
        'pump': 'pump',
        'smärta': 'pain',
        'ledvärk': 'joint pain',
        'ryggvärk': 'back pain',
        'artros': 'osteoarthritis',
        'kolesterol': 'cholesterol',
        'insulin': 'insulin',
        'blodflöde': 'blood flow',
        'cirkulation': 'circulation',
        'kollagen': 'collagen',
        'kollagensyntes': 'collagen synthesis',
        'keratin': 'keratin',
        'fiber': 'fiber',
        'probiotika': 'probiotics',
        'prebiotika': 'prebiotics',
        'enzymer': 'enzymes',
        'vitaminer': 'vitamins',
        'mineraler': 'minerals',
        'aminosyror': 'amino acids',
        'protein': 'protein',
        'fett': 'fat',
        'kolhydrater': 'carbohydrates',
        'vikt': 'weight',
        'viktminskning': 'weight loss',
        'mättnad': 'satiety',
        'aptit': 'appetite',
        'matsmältning': 'digestion',
        'gaser': 'gas',
        'diarré': 'diarrhea',
        'förstoppning': 'constipation',
        'halsbränna': 'heartburn',
        'magsår': 'stomach ulcer',
        'illamående': 'nausea',
        'kramp': 'cramp',
        'kramplösande': 'antispasmodic',
        'lugnande': 'calming',
        'sedativ': 'sedative',
        'stimulerande': 'stimulating',
        'vakenhet': 'alertness',
        'trötthet': 'fatigue',
        'återhämtning': 'recovery',
        'prestation': 'performance',
        'uthållighet': 'endurance',
        'styrka': 'strength',
        'kraft': 'power',
        'pump': 'pump',
        'muskelsparande': 'muscle sparing',
        'anabol': 'anabolic',
        'katabolt': 'catabolic',
        'antikatabolt': 'anticatabolic',
        'hormoner': 'hormones',
        'hormonbalans': 'hormone balance',
        'östrogen': 'estrogen',
        'progesteron': 'progesterone',
        'kortisol': 'cortisol',
        'serotonin': 'serotonin',
        'dopamin': 'dopamine',
        'noradrenalin': 'noradrenaline',
        'GABA': 'GABA',
        'acetylkolin': 'acetylcholine',
        'glutamat': 'glutamate',
        'glutamin': 'glutamine',
        'kreatin': 'creatine',
        'karnitin': 'carnitine',
        'taurin': 'taurine',
        'glycin': 'glycine',
        'arginin': 'arginine',
        'citrullin': 'citrulline',
        'lysine': 'lysine',
        'leucin': 'leucine',
        'glutamin': 'glutamine',
        'BCAA': 'BCAA',
        'EAA': 'EAA',
        'omega-3': 'omega-3',
        'omega-6': 'omega-6',
        'EPA': 'EPA',
        'DHA': 'DHA',
        'GLA': 'GLA',
        'CoQ10': 'CoQ10',
        'Q10': 'Q10',
        'NAD+': 'NAD+',
        'NMN': 'NMN',
        'resveratrol': 'resveratrol',
        'curcumin': 'curcumin',
        'quercetin': 'quercetin',
        'rutin': 'rutin',
        'hesperidin': 'hesperidin',
        'lutein': 'lutein',
        'zeaxantin': 'zeaxanthin',
        'lykopen': 'lycopene',
        'astaxantin': 'astaxanthin',
        'beta-karoten': 'beta-carotene',
        'vitamin A': 'vitamin A',
        'vitamin B': 'vitamin B',
        'vitamin C': 'vitamin C',
        'vitamin D': 'vitamin D',
        'vitamin E': 'vitamin E',
        'vitamin K': 'vitamin K',
        'folsyra': 'folic acid',
        'biotin': 'biotin',
        'niacin': 'niacin',
        'niacinamid': 'niacinamide',
        'riboflavin': 'riboflavin',
        'tiamin': 'thiamine',
        'pantotensyra': 'pantothenic acid',
        'pyridoxin': 'pyridoxine',
        'kobalamin': 'cobalamin',
        'kalcium': 'calcium',
        'magnesium': 'magnesium',
        'zink': 'zinc',
        'järn': 'iron',
        'selen': 'selenium',
        'jod': 'iodine',
        'koppar': 'copper',
        'mangan': 'manganese',
        'krom': 'chromium',
        'molybden': 'molybdenum',
        'bor': 'boron',
        'vanadin': 'vanadium',
        'kalium': 'potassium',
        'natrium': 'sodium',
        'fosfor': 'phosphorus',
        'svavel': 'sulfur',
        'kisel': 'silica',
        'klorofyll': 'chlorophyll',
        'glutation': 'glutathione',
        'melatonin': 'melatonin',
        'DHEA': 'DHEA',
        'pregnenolon': 'pregnenolone',
        'SAMe': 'SAMe',
        'TMG': 'TMG',
        'betain': 'betaine',
        'kreatin': 'creatine',
        'HMB': 'HMB',
        'BCAA': 'BCAA',
        'EAA': 'EAA',
        'whey': 'whey',
        'kasein': 'casein',
        'kollagen': 'collagen',
        'protein': 'protein',
        'fiber': 'fiber',
        'probiotika': 'probiotics',
        'prebiotika': 'prebiotics',
        'enzymer': 'enzymes',
        'digestive': 'digestive',
        'laktas': 'lactase',
        'gluten': 'gluten',
        'DAO': 'DAO',
        'bromelain': 'bromelain',
        'papain': 'papain',
        'serrapeptase': 'serrapeptase',
        'nattokinase': 'nattokinase',
        'laktobakterier': 'lactobacilli',
        'bifidobakterier': 'bifidobacteria',
        'saccharomyces': 'saccharomyces',
        'bacillus': 'bacillus',
        'inulin': 'inulin',
        'FOS': 'FOS',
        'GOS': 'GOS',
        'fruktooligosackarider': 'fructooligosaccharides',
        'galaktooligosackarider': 'galactooligosaccharides',
        'resistent stärkelse': 'resistant starch',
        'butyrat': 'butyrate',
        'kortisol': 'cortisol',
        'adrenalin': 'adrenaline',
        'noradrenalin': 'noradrenaline',
        'dopamin': 'dopamine',
        'serotonin': 'serotonin',
        'GABA': 'GABA',
        'glutamat': 'glutamate',
        'acetylkolin': 'acetylcholine',
        'histamin': 'histamine',
        'nitric oxide': 'nitric oxide',
        'kväveoxid': 'nitric oxide',
        'NO': 'NO',
        'cAMP': 'cAMP',
        'AMPK': 'AMPK',
        'mTOR': 'mTOR',
        'NAD+': 'NAD+',
        'NMN': 'NMN',
        'NR': 'NR',
        'sirtuiner': 'sirtuins',
        'sirtuin': 'sirtuin',
        'telomerer': 'telomeres',
        'autofagi': 'autophagy',
        'senolytisk': 'senolytic',
        'antioxidant': 'antioxidant',
        'oxidative stress': 'oxidative stress',
        'inflammation': 'inflammation',
        'antiinflammatorisk': 'anti-inflammatory',
        'immunmodulerande': 'immunomodulatory',
        'immunförstärkande': 'immune enhancing',
        'antiviral': 'antiviral',
        'antibakteriell': 'antibacterial',
        'antimikrobiell': 'antimicrobial',
        'antifungal': 'antifungal',
        'antiviral': 'antiviral',
        'antiparasitisk': 'antiparasitic',
        'cancer': 'cancer',
        'tumör': 'tumor',
        'metastas': 'metastasis',
        'cellcykel': 'cell cycle',
        'apoptos': 'apoptosis',
        'nekros': 'necrosis',
        'angiogenes': 'angiogenesis',
        'metastasering': 'metastasis',
        'cancerstöd': 'cancer support',
        'immunstöd': 'immune support',
        'immunförsvar': 'immune defense',
        'vita blodkroppar': 'white blood cells',
        'T-celler': 'T cells',
        'B-celler': 'B cells',
        'NK-celler': 'NK cells',
        'makrofager': 'macrophages',
        'neutrofiler': 'neutrophils',
        'eosinofiler': 'eosinophils',
        'basofiler': 'basophils',
        'mastceller': 'mast cells',
        'dendritiska celler': 'dendritic cells',
        'cytokiner': 'cytokines',
        'interferoner': 'interferons',
        'interleukiner': 'interleukins',
        'tumörnekrosfaktor': 'tumor necrosis factor',
        'TNF': 'TNF',
        'IL': 'IL',
        'IFN': 'IFN',
        'komplementsystemet': 'complement system',
        'fagocytos': 'phagocytosis',
        'antikroppar': 'antibodies',
        'IgG': 'IgG',
        'IgA': 'IgA',
        'IgM': 'IgM',
        'IgE': 'IgE',
        'IgD': 'IgD',
        'allergi': 'allergy',
        'allergisk': 'allergic',
        'hypersensitivitet': 'hypersensitivity',
        'anafylaxi': 'anaphylaxis',
        'histamin': 'histamine',
        'histaminintolerans': 'histamine intolerance',
        'mastocytos': 'mastocytosis',
        'MCAS': 'MCAS',
        'DAO': 'DAO',
        'HNMT': 'HNMT',
        'quercetin': 'quercetin',
        'vitamin C': 'vitamin C',
        'bromelain': 'bromelain',
        'stinging nettle': 'stinging nettle',
        'nässla': 'nettle',
        'brännässla': 'stinging nettle',
        'butterbur': 'butterbur',
        'petasites': 'petasites',
        'spirulina': 'spirulina',
        'chlorella': 'chlorella',
        'blue-green algae': 'blue-green algae',
        'cyanobakterier': 'cyanobacteria',
        'fucoidan': 'fucoidan',
        'astaxanthin': 'astaxanthin',
        'beta-carotene': 'beta-carotene',
        'lutein': 'lutein',
        'zeaxanthin': 'zeaxanthin',
        'lycopene': 'lycopene',
        'anthocyanins': 'anthocyanins',
        'antocyaniner': 'anthocyanins',
        'flavonoids': 'flavonoids',
        'flavonoider': 'flavonoids',
        'polyphenols': 'polyphenols',
        'polyfenoler': 'polyphenols',
        'tannins': 'tannins',
        'tanniner': 'tannins',
        'catechins': 'catechins',
        'katekiner': 'catechins',
        'EGCG': 'EGCG',
        'epigallocatechin gallate': 'epigallocatechin gallate',
        'resveratrol': 'resveratrol',
        'quercetin': 'quercetin',
        'rutin': 'rutin',
        'hesperidin': 'hesperidin',
        'naringenin': 'naringenin',
        'apigenin': 'apigenin',
        'luteolin': 'luteolin',
        'kaempferol': 'kaempferol',
        'myricetin': 'myricetin',
        'fisetin': 'fisetin',
        'curcumin': 'curcumin',
        'turmeric': 'turmeric',
        'gurkmeja': 'turmeric',
        'ginger': 'ginger',
        'ingefära': 'ginger',
        'garlic': 'garlic',
        'vitlök': 'garlic',
        'onion': 'onion',
        'lök': 'onion',
        'shallot': 'shallot',
        'schalottenlök': 'shallot',
        'leek': 'leek',
        'purjolök': 'leek',
        'chives': 'chives',
        'gräslök': 'chives',
        'asparagus': 'asparagus',
        'sparris': 'asparagus',
        'broccoli': 'broccoli',
        'broccoli': 'broccoli',
        'cauliflower': 'cauliflower',
        'blomkål': 'cauliflower',
        'cabbage': 'cabbage',
        'kål': 'cabbage',
        'brussels sprouts': 'brussels sprouts',
        'brysselkål': 'brussels sprouts',
        'kale': 'kale',
        'grönkål': 'kale',
        'collard greens': 'collard greens',
        'mustard greens': 'mustard greens',
        'watercress': 'watercress',
        'krasse': 'watercress',
        'arugula': 'arugula',
        'ruccola': 'arugula',
        'spinach': 'spinach',
        'spenat': 'spinach',
        'swiss chard': 'swiss chard',
        'mangold': 'swiss chard',
        'beet greens': 'beet greens',
        'betblad': 'beet greens',
        'turnip greens': 'turnip greens',
        'kålrabbi': 'kohlrabi',
        'radish': 'radish',
        'rädisa': 'radish',
        'daikon': 'daikon',
        'horseradish': 'horseradish',
        'pepparrot': 'horseradish',
        'wasabi': 'wasabi',
        'mustard': 'mustard',
        'senap': 'mustard',
        'honey': 'honey',
        'honung': 'honey',
        'manuka honey': 'manuka honey',
        'manukahonung': 'manuka honey',
        'propolis': 'propolis',
        'royal jelly': 'royal jelly',
        'bidrottninggelé': 'royal jelly',
        'bee pollen': 'bee pollen',
        'bipollen': 'bee pollen',
        'bee bread': 'bee bread',
        'bibröd': 'bee bread',
        'wax': 'wax',
        'vax': 'wax',
        'beeswax': 'beeswax',
        'bivax': 'beeswax',
        'mushrooms': 'mushrooms',
        'svamp': 'mushrooms',
        'svampar': 'mushrooms',
        'reishi': 'reishi',
        'lingzhi': 'lingzhi',
        'ganoderma': 'ganoderma',
        'shiitake': 'shiitake',
        'maitake': 'maitake',
        'hen of the woods': 'hen of the woods',
        'oyster mushroom': 'oyster mushroom',
        'ostronskivling': 'oyster mushroom',
        'enoki': 'enoki',
        'enokitake': 'enokitake',
        'nameko': 'nameko',
        'beech mushroom': 'beech mushroom',
        'buna-shimeji': 'buna-shimeji',
        'pioppino': 'pioppino',
        'black poplar': 'black poplar',
        'cypress': 'cypress',
        'velvet pioppini': 'velvet pioppini',
        'king trumpet': 'king trumpet',
        'eryngii': 'eryngii',
        'king oyster': 'king oyster',
        'pleurotus eryngii': 'pleurotus eryngii',
        'lions mane': 'lions mane',
        'lions mane mushroom': 'lions mane mushroom',
        'hericium erinaceus': 'hericium erinaceus',
        'yamabushitake': 'yamabushitake',
        'cordyceps': 'cordyceps',
        'cordyceps sinensis': 'cordyceps sinensis',
        'caterpillar fungus': 'caterpillar fungus',
        'winter worm summer grass': 'winter worm summer grass',
        'dong chong xia cao': 'dong chong xia cao',
        'CS-4': 'CS-4',
        'chaga': 'chaga',
        'inonotus obliquus': 'inonotus obliquus',
        'birch polypore': 'birch polypore',
        'tinder conk': 'tinder conk',
        'piptoporus betulinus': 'piptoporus betulinus',
        'turkey tail': 'turkey tail',
        'trametes versicolor': 'trametes versicolor',
        'coriolus versicolor': 'coriolus versicolor',
        'PSK': 'PSK',
        'krestin': 'krestin',
        'PSP': 'PSP',
        'polysaccharide peptide': 'polysaccharide peptide',
        'polysackaridpeptid': 'polysaccharide peptide',
        'polysaccharides': 'polysaccharides',
        'polysackarider': 'polysaccharides',
        'beta-glucans': 'beta-glucans',
        'beta-glukaner': 'beta-glucans',
        'beta-1,3-glucan': 'beta-1,3-glucan',
        'beta-1,6-glucan': 'beta-1,6-glucan',
        'lentinan': 'lentinan',
        'schizophyllan': 'schizophyllan',
        'sonifilan': 'sonifilan',
        'grifolan': 'grifolan',
        'pleuran': 'pleuran',
        'pleurotus ostreatus': 'pleurotus ostreatus',
        'AHCC': 'AHCC',
        'active hexose correlated compound': 'active hexose correlated compound',
        'aktiverat hexoskorrelerat ämne': 'active hexose correlated compound',
        'tremella': 'tremella',
        'tremella fuciformis': 'tremella fuciformis',
        'snow fungus': 'snow fungus',
        'silver ear': 'silver ear',
        'white jelly mushroom': 'white jelly mushroom',
        'agaricus blazei': 'agaricus blazei',
        'agaricus brasiliensis': 'agaricus brasiliensis',
        'agaricus subrufescens': 'agaricus subrufescens',
        'almond mushroom': 'almond mushroom',
        'mandelsvamp': 'almond mushroom',
        'royal sun agaricus': 'royal sun agaricus',
        'himematsutake': 'himematsutake',
        'cogumelo do sol': 'cogumelo do sol',
        'cogumelo do sol': 'cogumelo do sol',
        'cogumelo do sol': 'cogumelo do sol',
        'cogumelo do sol': 'cogumelo do sol',
    }
    
    # Apply translations
    result = text
    for swedish, english in translations.items():
        # Case-insensitive replacement, preserving original case
        pattern = re.compile(re.escape(swedish), re.IGNORECASE)
        result = pattern.sub(english, result)
    
    return result

def translate_row(row):
    """Translate a single CSV row from Swedish to English."""
    translated = row.copy()
    
    # Translate research_status (column index 2)
    if len(translated) > 2 and translated[2] in STATUS_MAP:
        translated[2] = STATUS_MAP[translated[2]]
    
    # Translate interaction_risk (column index 7)
    if len(translated) > 7 and translated[7] in RISK_MAP:
        translated[7] = RISK_MAP[translated[7]]
    
    # Translate text fields (dosing_notes, bioavailability_notes)
    # Column indices: 5=dosing_notes, 6=bioavailability_notes
    for idx in [5, 6]:
        if len(translated) > idx and translated[idx]:
            translated[idx] = translate_text(translated[idx])
    
    return translated

def main():
    input_file = 'Börja utforska - Börja utforska.csv'
    output_file = 'supplements-english.csv'
    
    rows = []
    header_found = False
    header_row = None
    
    # Read the CSV file
    with open(input_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row_num, row in enumerate(reader, 1):
            # Check if this is the header row
            if len(row) > 0 and 'name_sv' in row[0].lower():
                header_row = row
                header_found = True
                rows.append(row)  # Keep header as-is
                continue
            
            # Translate data rows
            if len(row) >= 10:  # Ensure we have all columns
                translated = translate_row(row)
                rows.append(translated)
            else:
                rows.append(row)  # Keep malformed rows as-is
    
    # Write the translated CSV
    with open(output_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(rows)
    
    print(f"Translation complete! {len(rows)} rows written to {output_file}")
    print(f"Header found: {header_found}")

if __name__ == '__main__':
    main()
