#!/usr/bin/env python3
"""
Simple translation script for Swedish supplement CSV to English.
Handles status codes, risk levels, and common Swedish medical terms.
"""

import csv
import re

# Direct mappings
STATUS_MAP = {'Grön': 'Green', 'Blå': 'Blue', 'Röd': 'Red'}
RISK_MAP = {'Låg': 'Low', 'Medium': 'Medium', 'Hög': 'High'}

# Common Swedish to English term replacements
TERM_REPLACEMENTS = [
    # Status and risk
    (r'\bGrön\b', 'Green'),
    (r'\bBlå\b', 'Blue'),
    (r'\bRöd\b', 'Red'),
    (r'\bLåg\b', 'Low'),
    (r'\bHög\b', 'High'),
    (r'\bMedium\b', 'Medium'),
    
    # Common medical/supplement terms
    (r'\bSlem\b', 'Mucus'),
    (r'\blever\b', 'liver'),
    (r'\bhud\b', 'skin'),
    (r'\bhår\b', 'hair'),
    (r'\bnaglar\b', 'nails'),
    (r'\bögon\b', 'eyes'),
    (r'\bhjärta\b', 'heart'),
    (r'\bhjärna\b', 'brain'),
    (r'\bmage\b', 'stomach'),
    (r'\btarm\b', 'intestine'),
    (r'\bleder\b', 'joints'),
    (r'\bmuskler\b', 'muscles'),
    (r'\bben\b', 'bones'),
    (r'\bprostata\b', 'prostate'),
    (r'\bblodtryck\b', 'blood pressure'),
    (r'\bblodsocker\b', 'blood sugar'),
    (r'\bimmun\b', 'immune'),
    (r'\bimmunförsvar\b', 'immune defense'),
    (r'\benergi\b', 'energy'),
    (r'\bsömn\b', 'sleep'),
    (r'\bstress\b', 'stress'),
    (r'\bångest\b', 'anxiety'),
    (r'\bdepression\b', 'depression'),
    (r'\bhumör\b', 'mood'),
    (r'\bminne\b', 'memory'),
    (r'\bfokus\b', 'focus'),
    (r'\blibido\b', 'libido'),
    (r'\btestosteron\b', 'testosterone'),
    (r'\binflammation\b', 'inflammation'),
    (r'\bantioxidant\b', 'antioxidant'),
    (r'\bdetox\b', 'detox'),
    (r'\bmetabolism\b', 'metabolism'),
    (r'\bfettförbränning\b', 'fat burning'),
    (r'\bmuskeltillväxt\b', 'muscle growth'),
    (r'\bsmärta\b', 'pain'),
    (r'\bledvärk\b', 'joint pain'),
    (r'\bryggvärk\b', 'back pain'),
    (r'\bartros\b', 'osteoarthritis'),
    (r'\bkolesterol\b', 'cholesterol'),
    (r'\binsulin\b', 'insulin'),
    (r'\bblodflöde\b', 'blood flow'),
    (r'\bcirkulation\b', 'circulation'),
    (r'\bkollagen\b', 'collagen'),
    (r'\bfiber\b', 'fiber'),
    (r'\bprobiotika\b', 'probiotics'),
    (r'\bprebiotika\b', 'prebiotics'),
    (r'\benzymer\b', 'enzymes'),
    (r'\bmatsmältning\b', 'digestion'),
    (r'\bgaser\b', 'gas'),
    (r'\bdiarré\b', 'diarrhea'),
    (r'\bförstoppning\b', 'constipation'),
    (r'\bhalsbränna\b', 'heartburn'),
    (r'\bmagsår\b', 'stomach ulcer'),
    (r'\billamående\b', 'nausea'),
    (r'\bkramp\b', 'cramp'),
    (r'\blugnande\b', 'calming'),
    (r'\bsedativ\b', 'sedative'),
    (r'\btrötthet\b', 'fatigue'),
    (r'\båterhämtning\b', 'recovery'),
    (r'\bprestation\b', 'performance'),
    (r'\buthållighet\b', 'endurance'),
    (r'\bstyrka\b', 'strength'),
    (r'\bhormoner\b', 'hormones'),
    (r'\böstrogen\b', 'estrogen'),
    (r'\bkortisol\b', 'cortisol'),
    (r'\bserotonin\b', 'serotonin'),
    (r'\bdopamin\b', 'dopamine'),
    (r'\bkreatin\b', 'creatine'),
    (r'\bkarnitin\b', 'carnitine'),
    (r'\btaurin\b', 'taurine'),
    (r'\bglycin\b', 'glycine'),
    (r'\barginin\b', 'arginine'),
    (r'\bcitrullin\b', 'citrulline'),
    (r'\bmagnesium\b', 'magnesium'),
    (r'\bzink\b', 'zinc'),
    (r'\bjärn\b', 'iron'),
    (r'\bselen\b', 'selenium'),
    (r'\bjod\b', 'iodine'),
    (r'\bkoppar\b', 'copper'),
    (r'\bkalcium\b', 'calcium'),
    (r'\bkalium\b', 'potassium'),
    (r'\bmelatonin\b', 'melatonin'),
    (r'\bglutation\b', 'glutathione'),
    (r'\bklorofyll\b', 'chlorophyll'),
    (r'\bkollagensyntes\b', 'collagen synthesis'),
    (r'\bkeratin\b', 'keratin'),
    (r'\bvitaminer\b', 'vitamins'),
    (r'\bmineraler\b', 'minerals'),
    (r'\baminosyror\b', 'amino acids'),
    (r'\bprotein\b', 'protein'),
    (r'\bfett\b', 'fat'),
    (r'\bvikt\b', 'weight'),
    (r'\baptit\b', 'appetite'),
    (r'\bmättnad\b', 'satiety'),
    (r'\ballergi\b', 'allergy'),
    (r'\bantiviral\b', 'antiviral'),
    (r'\bantibakteriell\b', 'antibacterial'),
    (r'\bantimikrobiell\b', 'antimicrobial'),
    (r'\bkortisol\b', 'cortisol'),
    (r'\bGABA\b', 'GABA'),
    (r'\bacetylkolin\b', 'acetylcholine'),
    (r'\bglutamat\b', 'glutamate'),
    (r'\bhistamin\b', 'histamine'),
    (r'\bkväveoxid\b', 'nitric oxide'),
    (r'\bNO\b', 'NO'),
    (r'\bNAD\+\b', 'NAD+'),
    (r'\bNMN\b', 'NMN'),
    (r'\bCoQ10\b', 'CoQ10'),
    (r'\bQ10\b', 'Q10'),
    (r'\bEPA\b', 'EPA'),
    (r'\bDHA\b', 'DHA'),
    (r'\bGLA\b', 'GLA'),
    (r'\bomega-3\b', 'omega-3'),
    (r'\bomega-6\b', 'omega-6'),
    (r'\bBCAA\b', 'BCAA'),
    (r'\bEAA\b', 'EAA'),
    (r'\bwhey\b', 'whey'),
    (r'\bkasein\b', 'casein'),
    (r'\bcurcumin\b', 'curcumin'),
    (r'\bresveratrol\b', 'resveratrol'),
    (r'\bquercetin\b', 'quercetin'),
    (r'\brutin\b', 'rutin'),
    (r'\bhesperidin\b', 'hesperidin'),
    (r'\blutein\b', 'lutein'),
    (r'\bzeaxantin\b', 'zeaxanthin'),
    (r'\blykopen\b', 'lycopene'),
    (r'\bastaxantin\b', 'astaxanthin'),
    (r'\bbeta-karoten\b', 'beta-carotene'),
    (r'\bgurkmeja\b', 'turmeric'),
    (r'\bingefära\b', 'ginger'),
    (r'\bvitlök\b', 'garlic'),
    (r'\bpropolis\b', 'propolis'),
    (r'\bhonung\b', 'honey'),
    (r'\bmanukahonung\b', 'manuka honey'),
    (r'\bsvamp\b', 'mushroom'),
    (r'\breishi\b', 'reishi'),
    (r'\bshiitake\b', 'shiitake'),
    (r'\bmaitake\b', 'maitake'),
    (r'\bcordyceps\b', 'cordyceps'),
    (r'\bchaga\b', 'chaga'),
    (r'\bturkey tail\b', 'turkey tail'),
    (r'\blions mane\b', 'lions mane'),
    (r'\btremella\b', 'tremella'),
    (r'\bagaricus\b', 'agaricus'),
    (r'\bprobiotika\b', 'probiotics'),
    (r'\bprebiotika\b', 'prebiotics'),
    (r'\binulin\b', 'inulin'),
    (r'\bFOS\b', 'FOS'),
    (r'\bGOS\b', 'GOS'),
    (r'\bbutyrat\b', 'butyrate'),
    (r'\bDHEA\b', 'DHEA'),
    (r'\bpregnenolon\b', 'pregnenolone'),
    (r'\bSAMe\b', 'SAMe'),
    (r'\bTMG\b', 'TMG'),
    (r'\bbetain\b', 'betaine'),
    (r'\bHMB\b', 'HMB'),
    (r'\bNAC\b', 'NAC'),
    (r'\b5-HTP\b', '5-HTP'),
    (r'\bL-Dopa\b', 'L-Dopa'),
    (r'\bL-Tyrosin\b', 'L-Tyrosine'),
    (r'\bL-Tryptofan\b', 'L-Tryptophan'),
    (r'\bL-Glutamin\b', 'L-Glutamine'),
    (r'\bL-Arginin\b', 'L-Arginine'),
    (r'\bL-Citrullin\b', 'L-Citrulline'),
    (r'\bL-Lysin\b', 'L-Lysine'),
    (r'\bL-Leucin\b', 'L-Leucine'),
    (r'\bL-Karnitin\b', 'L-Carnitine'),
    (r'\bAlpha-GPC\b', 'Alpha-GPC'),
    (r'\bCitikolin\b', 'Citicoline'),
    (r'\bCDP-Choline\b', 'CDP-Choline'),
    (r'\bPhosphatidylserin\b', 'Phosphatidylserine'),
    (r'\bPhosphatidylserine\b', 'Phosphatidylserine'),
    (r'\bPhosphatidic Acid\b', 'Phosphatidic Acid'),
    (r'\bPA\b', 'PA'),
    (r'\bCreatine\b', 'Creatine'),
    (r'\bCreatine Monohydrate\b', 'Creatine Monohydrate'),
    (r'\bCreatine HCL\b', 'Creatine HCL'),
    (r'\bKre-Alkalyn\b', 'Kre-Alkalyn'),
    (r'\bBeta-Alanine\b', 'Beta-Alanine'),
    (r'\bHMB\b', 'HMB'),
    (r'\bEcdysterone\b', 'Ecdysterone'),
    (r'\bTurkesterone\b', 'Turkesterone'),
    (r'\bLaxogenin\b', 'Laxogenin'),
    (r'\bArachidonic Acid\b', 'Arachidonic Acid'),
    (r'\bAA\b', 'AA'),
    (r'\bConjugated Linoleic Acid\b', 'Conjugated Linoleic Acid'),
    (r'\bCLA\b', 'CLA'),
    (r'\bMCT Oil\b', 'MCT Oil'),
    (r'\bMCT\b', 'MCT'),
    (r'\bCaprylic Acid\b', 'Caprylic Acid'),
    (r'\bC8\b', 'C8'),
    (r'\bC10\b', 'C10'),
    (r'\bCapric Acid\b', 'Capric Acid'),
    (r'\bLauric Acid\b', 'Lauric Acid'),
    (r'\bC12\b', 'C12'),
    (r'\bMonolaurin\b', 'Monolaurin'),
    (r'\bGlycerol\b', 'Glycerol'),
    (r'\bGlycerpump\b', 'Glycerpump'),
    (r'\bSodium Bicarbonate\b', 'Sodium Bicarbonate'),
    (r'\bElectrolytes\b', 'Electrolytes'),
    (r'\bNa\b', 'Na'),
    (r'\bK\b', 'K'),
    (r'\bMg\b', 'Mg'),
    (r'\bCa\b', 'Ca'),
    (r'\bP\b', 'P'),
    (r'\bCl\b', 'Cl'),
    (r'\bS\b', 'S'),
    (r'\bFe\b', 'Fe'),
    (r'\bZn\b', 'Zn'),
    (r'\bCu\b', 'Cu'),
    (r'\bMn\b', 'Mn'),
    (r'\bCr\b', 'Cr'),
    (r'\bMo\b', 'Mo'),
    (r'\bSe\b', 'Se'),
    (r'\bI\b', 'I'),
    (r'\bB\b', 'B'),
    (r'\bSi\b', 'Si'),
    (r'\bV\b', 'V'),
    (r'\bNi\b', 'Ni'),
    (r'\bCo\b', 'Co'),
    (r'\bF\b', 'F'),
    (r'\bLi\b', 'Li'),
    (r'\bRb\b', 'Rb'),
    (r'\bCs\b', 'Cs'),
    (r'\bFr\b', 'Fr'),
    (r'\bBe\b', 'Be'),
    (r'\bMg\b', 'Mg'),
    (r'\bCa\b', 'Ca'),
    (r'\bSr\b', 'Sr'),
    (r'\bBa\b', 'Ba'),
    (r'\bRa\b', 'Ra'),
    (r'\bSc\b', 'Sc'),
    (r'\bTi\b', 'Ti'),
    (r'\bV\b', 'V'),
    (r'\bCr\b', 'Cr'),
    (r'\bMn\b', 'Mn'),
    (r'\bFe\b', 'Fe'),
    (r'\bCo\b', 'Co'),
    (r'\bNi\b', 'Ni'),
    (r'\bCu\b', 'Cu'),
    (r'\bZn\b', 'Zn'),
    (r'\bGa\b', 'Ga'),
    (r'\bGe\b', 'Ge'),
    (r'\bAs\b', 'As'),
    (r'\bSe\b', 'Se'),
    (r'\bBr\b', 'Br'),
    (r'\bKr\b', 'Kr'),
    (r'\bRb\b', 'Rb'),
    (r'\bSr\b', 'Sr'),
    (r'\bY\b', 'Y'),
    (r'\bZr\b', 'Zr'),
    (r'\bNb\b', 'Nb'),
    (r'\bMo\b', 'Mo'),
    (r'\bTc\b', 'Tc'),
    (r'\bRu\b', 'Ru'),
    (r'\bRh\b', 'Rh'),
    (r'\bPd\b', 'Pd'),
    (r'\bAg\b', 'Ag'),
    (r'\bCd\b', 'Cd'),
    (r'\bIn\b', 'In'),
    (r'\bSn\b', 'Sn'),
    (r'\bSb\b', 'Sb'),
    (r'\bTe\b', 'Te'),
    (r'\bI\b', 'I'),
    (r'\bXe\b', 'Xe'),
    (r'\bCs\b', 'Cs'),
    (r'\bBa\b', 'Ba'),
    (r'\bLa\b', 'La'),
    (r'\bCe\b', 'Ce'),
    (r'\bPr\b', 'Pr'),
    (r'\bNd\b', 'Nd'),
    (r'\bPm\b', 'Pm'),
    (r'\bSm\b', 'Sm'),
    (r'\bEu\b', 'Eu'),
    (r'\bGd\b', 'Gd'),
    (r'\bTb\b', 'Tb'),
    (r'\bDy\b', 'Dy'),
    (r'\bHo\b', 'Ho'),
    (r'\bEr\b', 'Er'),
    (r'\bTm\b', 'Tm'),
    (r'\bYb\b', 'Yb'),
    (r'\bLu\b', 'Lu'),
    (r'\bHf\b', 'Hf'),
    (r'\bTa\b', 'Ta'),
    (r'\bW\b', 'W'),
    (r'\bRe\b', 'Re'),
    (r'\bOs\b', 'Os'),
    (r'\bIr\b', 'Ir'),
    (r'\bPt\b', 'Pt'),
    (r'\bAu\b', 'Au'),
    (r'\bHg\b', 'Hg'),
    (r'\bTl\b', 'Tl'),
    (r'\bPb\b', 'Pb'),
    (r'\bBi\b', 'Bi'),
    (r'\bPo\b', 'Po'),
    (r'\bAt\b', 'At'),
    (r'\bRn\b', 'Rn'),
    (r'\bFr\b', 'Fr'),
    (r'\bRa\b', 'Ra'),
    (r'\bAc\b', 'Ac'),
    (r'\bTh\b', 'Th'),
    (r'\bPa\b', 'Pa'),
    (r'\bU\b', 'U'),
    (r'\bNp\b', 'Np'),
    (r'\bPu\b', 'Pu'),
    (r'\bAm\b', 'Am'),
    (r'\bCm\b', 'Cm'),
    (r'\bBk\b', 'Bk'),
    (r'\bCf\b', 'Cf'),
    (r'\bEs\b', 'Es'),
    (r'\bFm\b', 'Fm'),
    (r'\bMd\b', 'Md'),
    (r'\bNo\b', 'No'),
    (r'\bLr\b', 'Lr'),
    (r'\bRf\b', 'Rf'),
    (r'\bDb\b', 'Db'),
    (r'\bSg\b', 'Sg'),
    (r'\bBh\b', 'Bh'),
    (r'\bHs\b', 'Hs'),
    (r'\bMt\b', 'Mt'),
    (r'\bDs\b', 'Ds'),
    (r'\bRg\b', 'Rg'),
    (r'\bCn\b', 'Cn'),
    (r'\bNh\b', 'Nh'),
    (r'\bFl\b', 'Fl'),
    (r'\bMc\b', 'Mc'),
    (r'\bLv\b', 'Lv'),
    (r'\bTs\b', 'Ts'),
    (r'\bOg\b', 'Og'),
]

def translate_text(text):
    """Translate Swedish text to English."""
    if not text or text == '-':
        return text
    
    result = text
    for pattern, replacement in TERM_REPLACEMENTS:
        result = re.sub(pattern, replacement, result, flags=re.IGNORECASE)
    
    return result

def translate_row(row):
    """Translate a single CSV row."""
    if len(row) < 10:
        return row
    
    translated = list(row)
    
    # Translate research_status (index 2)
    if translated[2] in STATUS_MAP:
        translated[2] = STATUS_MAP[translated[2]]
    
    # Translate interaction_risk (index 7) 
    if translated[7] in RISK_MAP:
        translated[7] = RISK_MAP[translated[7]]
    
    # Translate text fields (indices 5, 6)
    for idx in [5, 6]:
        if translated[idx]:
            translated[idx] = translate_text(translated[idx])
    
    return translated

def main():
    input_file = 'Börja utforska - Börja utforska.csv'
    output_file = 'supplements-english.csv'
    
    rows = []
    
    with open(input_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) > 0 and 'name_sv' in row[0].lower():
                # Header row - keep as is
                rows.append(row)
            elif len(row) >= 10:
                # Data row - translate
                rows.append(translate_row(row))
            else:
                # Keep malformed rows
                rows.append(row)
    
    with open(output_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(rows)
    
    print(f"Translation complete! {len(rows)} rows written to {output_file}")

if __name__ == '__main__':
    main()
